// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjhwDCNCDQbKOIWWBrthjmbij9SC-qMyg',
    appId: '1:909408910094:web:57cbab0ebca3c5840f355f',
    messagingSenderId: '909408910094',
    projectId: 'budget-app-108',
    authDomain: 'budget-app-108.firebaseapp.com',
    storageBucket: 'budget-app-108.appspot.com',
    measurementId: 'G-J04JCMR5VS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUsCyVAHPZW542SOgUFy2VB38kP0MLTus',
    appId: '1:909408910094:android:f0199bae70ae319e0f355f',
    messagingSenderId: '909408910094',
    projectId: 'budget-app-108',
    storageBucket: 'budget-app-108.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfcpoQqAN5dAyHmK9dHeqOhLRCPK9YuMA',
    appId: '1:909408910094:ios:542c65fe7ac8851b0f355f',
    messagingSenderId: '909408910094',
    projectId: 'budget-app-108',
    storageBucket: 'budget-app-108.appspot.com',
    iosBundleId: 'com.example.budgetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfcpoQqAN5dAyHmK9dHeqOhLRCPK9YuMA',
    appId: '1:909408910094:ios:542c65fe7ac8851b0f355f',
    messagingSenderId: '909408910094',
    projectId: 'budget-app-108',
    storageBucket: 'budget-app-108.appspot.com',
    iosBundleId: 'com.example.budgetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjhwDCNCDQbKOIWWBrthjmbij9SC-qMyg',
    appId: '1:909408910094:web:5b2ed8ed94108b8a0f355f',
    messagingSenderId: '909408910094',
    projectId: 'budget-app-108',
    authDomain: 'budget-app-108.firebaseapp.com',
    storageBucket: 'budget-app-108.appspot.com',
    measurementId: 'G-L3Y0DR7Q8W',
  );
}
